### PR TITLE
Allow passing through a message key for Kafka executor

### PR DESCRIPTION
**Pull request by ConductorPete**
Enable the ability to use a message key in the Kafka executor. The key is fairly useful/core functionality for Kafka: 
- https://stackoverflow.com/a/29515696
- https://stackoverflow.com/a/61912094

### CODE REVIEW

**Comment by ConductorPete** [comment]
@victorcoder @yvanoers I'm not sure about your process/milestones/etc, but is there anything else required from my end to get this merged in?

**Comment by yvanoers** [comment]
@ConductorPete I typically refrain from merging. In this case however, @victorcoder has already seen and approved the PR, so I'm ok with doing it.
I don't know when this will end up in a release, though.

**Comment by ConductorPete** [comment]
Thanks for the merge!

**Comment by victorcoder** [comment]
Yeah thx @yvanoers, been a bit busy lately.

**Pull request merged**
