### PR TITLE
Fix multitag cardinality bug

### LINKED ISSUE #821: Intermittent 'no target nodes found to run job'
**Describe the bug**

Whilst trying to debug #798, I started with an empty cluster, with the hope to build it up again.

I have a simple job that runs with tags on any of the three servers (no agents) in my cluster. All three servers have the same tags.

The job runs every minute, and the majority of the time I get: `msg="job: Error running job" error="no target nodes found to run job temp-clusterbackup_private_database"` (For a job that runs every minute, it's run 3 times in 10 minutes).

The cluster only has two jobs, this one that runs every minute, and another that runs daily. As the cluster has only existed for an hour, the other job has not run.

**Cluster Config Files**

(All 3 nodes have the same config)

```yaml
server: true
raft-multiplier: 1
# 2 servers min for our cluster
bootstrap-expect: 2
node-name: MC-P-SQL-3.example.com
log-level: debug
data-dir: /var/lib/dkron
enable-prometheus: true
tags:
   vmclass: database
   zone: private
datacenter: mc
encrypt: -bla-
join:
  - 192.168.171.21
  - 192.168.171.22
  - 192.168.171.23
  - 192.168.171.24
mail-host: localhost
mail-port: 25
mail-from: cron@MC-P-SQL-3.example.com
```

MC-P-SQL-1 to 3 are running (21-23)

> dkron raft list-peers
```
Node                    ID                      Address              State     Voter
MC-P-SQL-1.example.com  MC-P-SQL-1.example.com  192.168.171.21:6868  follower  true
MC-P-SQL-2.example.com  MC-P-SQL-2.example.com  192.168.171.22:6868  leader    true
MC-P-SQL-3.example.com  MC-P-SQL-3.example.com  192.168.171.23:6868  follower  true
```

**Expected behavior**

Job is meant to run every minute

**Job json**
```json
{
  "name": "temp-clusterbackup_private_database",
  "displayname": "",
  "timezone": "",
  "schedule": "0 * * * * *",
  "owner": "root",
  "owner_email": "",
  "success_count": 4,
  "error_count": 0,
  "last_success": "2020-09-16T13:34:00.053599307Z",
  "last_error": null,
  "disabled": false,
  "tags": {
    "vmclass": "database:1",
    "zone": "private:1"
  },
  "metadata": null,
  "retries": 0,
  "dependent_jobs": null,
  "parent_job": "",
  "processors": {
    "files": {
      "forward": "false",
      "log_dir": "/var/log/dkron-jobs/temp-clusterbackup_private_database"
    }
  },
  "concurrency": "forbid",
  "executor": "shell",
  "executor_config": {
    "command": "su -s /bin/bash -c \"umask 0002;  date\" example-user"
  },
  "status": "success",
  "next": "2020-09-16T13:37:00Z"
}
```

**Screenshots**

image

**Specifications:**

 - OS: CentOS 7
 - Version: dkron 3.0.5

**Logs from leader**

```
dkron[243398]: time="2020-09-16T14:20:58+01:00" level=info msg="[GIN] 2020/09/16 - 14:20:58 | 301 |        38.2µs |  192.168.171.12 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:20:59+01:00" level=info msg="[GIN] 2020/09/16 - 14:20:59 | 301 |        35.9µs |  192.168.171.11 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="job: Run job" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com schedule="0 * * * * *"
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="store: Retrieved job from datastore" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="fsm: received command" command=0 node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="store: Retrieved job from datastore" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="store: Setting job" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="agent: Filtered nodes to run" node=MC-P-SQL-2.example.com nodes="map[MC-P-SQL-1.example.com:192.168.171.21:6868]"
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=info msg="agent: Calling AgentRun" job_name=temp-clusterbackup_private_database node="192.168.171.21:6868"
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="grpc: received execution stream" key=1600262460014475903-MC-P-SQL-1.example.com node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="grpc: Received SetExecution" execution=1600262460014475903-MC-P-SQL-1.example.com node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="fsm: received command" command=2 node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="store: Setting key" execution="executions:temp-clusterbackup_private_database:1600262460014475903-MC-P-SQL-1.example.com" finished="0001-01-01 00:00:00 +0000 UTC" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="grpc: received execution stream" key=1600262460014475903-MC-P-SQL-1.example.com node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="grpc: received execution stream" key=1600262460014475903-MC-P-SQL-1.example.com node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="grpc: Received execution done" from=MC-P-SQL-1.example.com group=1600262460006354424 job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="store: Retrieved job from datastore" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=info msg="grpc: Processing execution with plugin" node=MC-P-SQL-2.example.com plugin=files
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="time=\"2020-09-16T14:21:00+01:00\" level=info msg=\"Forwarding set to: false\"" node=MC-P-SQL-2.example.com subsystem_name=plugins.dkron-processor-files
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="time=\"2020-09-16T14:21:00+01:00\" level=info msg=\"Log dir set to: /var/log/dkron-jobs/temp-clusterbackup_private_database\"" node=MC-P-SQL-2.example.com subsystem_name=plugins.dkron-processor-files
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="time=\"2020-09-16T14:21:00+01:00\" level=info msg=\"files: Writing file\" file=/var/log/dkron-jobs/temp-clusterbackup_private_database/1600262460014475903-MC-P-SQL-1.example.com.log" node=MC-P-SQL-2.example.com subsystem_name=plugins.dkron-processor-files
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="fsm: received command" command=4 node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="fsm: Setting execution" execution=1600262460014475903-MC-P-SQL-1.example.com node=MC-P-SQL-2.example.com output=/var/log/dkron-jobs/temp-clusterbackup_private_database/1600262460014475903-MC-P-SQL-1.example.com.log
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="store: Retrieved job from datastore" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="store: Setting job" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="store: Retrieved job from datastore" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=debug msg="grpc: Response from method" from=MC-P-SQL-2.example.com method=ExecutionDone node=MC-P-SQL-2.example.com payload=saved server_addr="192.168.171.22:6868"
dkron[243398]: time="2020-09-16T14:21:00+01:00" level=info msg="[GIN] 2020/09/16 - 14:21:00 | 301 |        36.5µs |  192.168.171.12 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:01+01:00" level=info msg="[GIN] 2020/09/16 - 14:21:01 | 301 |          31µs |  192.168.171.11 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:03+01:00" level=info msg="[GIN] 2020/09/16 - 14:21:03 | 301 |          37µs |  192.168.171.12 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:53+01:00" level=info msg="2020/09/16 14:21:53 [DEBUG] memberlist: Initiating push/pull sync with: MC-P-SQL-1.example.com 192.168.171.21:8946"
dkron[243398]: time="2020-09-16T14:21:57+01:00" level=info msg="[GIN] 2020/09/16 - 14:21:57 | 301 |        44.2µs |  192.168.171.11 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:58+01:00" level=info msg="[GIN] 2020/09/16 - 14:21:58 | 301 |        35.1µs |  192.168.171.12 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:21:59+01:00" level=info msg="[GIN] 2020/09/16 - 14:21:59 | 301 |        39.4µs |  192.168.171.11 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:00+01:00" level=debug msg="job: Run job" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com schedule="0 * * * * *"
dkron[243398]: time="2020-09-16T14:22:00+01:00" level=debug msg="store: Retrieved job from datastore" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:00+01:00" level=debug msg="fsm: received command" command=0 node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:00+01:00" level=debug msg="store: Retrieved job from datastore" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:00+01:00" level=debug msg="store: Setting job" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:00+01:00" level=error msg="job: Error running job" error="no target nodes found to run job temp-clusterbackup_private_database" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:00+01:00" level=info msg="[GIN] 2020/09/16 - 14:22:00 | 301 |          36µs |  192.168.171.12 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:14+01:00" level=info msg="[GIN] 2020/09/16 - 14:22:14 | 301 |          36µs |  192.168.171.12 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:15+01:00" level=info msg="[GIN] 2020/09/16 - 14:22:15 | 301 |        37.9µs |  192.168.171.11 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:16+01:00" level=info msg="2020/09/16 14:22:16 [DEBUG] memberlist: Stream connection from=192.168.171.23:57214"
dkron[243398]: time="2020-09-16T14:22:16+01:00" level=info msg="[GIN] 2020/09/16 - 14:22:16 | 301 |        37.8µs |  192.168.171.12 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:23+01:00" level=info msg="[GIN] 2020/09/16 - 14:22:23 | 301 |        37.6µs |  192.168.171.11 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:23+01:00" level=info msg="2020/09/16 14:22:23 [DEBUG] memberlist: Initiating push/pull sync with: MC-P-SQL-3.example.com 192.168.171.23:8946"
dkron[243398]: time="2020-09-16T14:22:24+01:00" level=info msg="[GIN] 2020/09/16 - 14:22:24 | 301 |        36.9µs |  192.168.171.12 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:25+01:00" level=info msg="[GIN] 2020/09/16 - 14:22:25 | 301 |          43µs |  192.168.171.11 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:26+01:00" level=info msg="[GIN] 2020/09/16 - 14:22:26 | 301 |        39.2µs |  192.168.171.12 | GET      \"/\"" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:22:53+01:00" level=info msg="2020/09/16 14:22:53 [DEBUG] memberlist: Initiating push/pull sync with: MC-P-SQL-1.example.com 192.168.171.21:8946"
dkron[243398]: time="2020-09-16T14:23:00+01:00" level=debug msg="job: Run job" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com schedule="0 * * * * *"
dkron[243398]: time="2020-09-16T14:23:00+01:00" level=debug msg="store: Retrieved job from datastore" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:23:00+01:00" level=debug msg="fsm: received command" command=0 node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:23:00+01:00" level=debug msg="store: Retrieved job from datastore" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:23:00+01:00" level=debug msg="store: Setting job" job=temp-clusterbackup_private_database node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:23:00+01:00" level=error msg="job: Error running job" error="no target nodes found to run job temp-clusterbackup_private_database" node=MC-P-SQL-2.example.com
dkron[243398]: time="2020-09-16T14:23:03+01:00" level=info msg="2020/09/16 14:23:03 [DEBUG] memberlist: Stream connection from=192.168.171.21:48098"
```

### PR DESCRIPTION
**Pull request by yvanoers**
Fixes #821.

### CODE REVIEW

**Review by victorcoder — CHANGES_REQUESTED** [review]
Good job here! thx @yvanoers, just one observation, I had a hard time reviewing because `filterNodes` function modifies `execNodes` inside, this is an unexpected change, I tend to prefer returning the modified structure for clarity, WDYT?

**Comment by yvanoers** [comment]
I made the function return everything it touches. Also reduced the side effect of the tags changing and now returning new value.
I didn't want to create a new map to eliminate the execNodes side effect, because it would hit performance and mem use.

To really properly fix the lengthiness of these functions, I would create a separate struct with accompanying functions and put it all in a separate file. I didn't want to go that way, though, because it seems like an extensive solution to a relatively small problem.

Anyway, I pushed some changes, have a look and let me know your thoughts, @victorcoder !

**Review by victorcoder — APPROVED** [review]
This looks much more intuitive, thanks!

**Comment by victorcoder** [comment]
Hi @yvanoers I'm receiving reports of this change affecting the evenly balancing of executions in nodes
image

I did not have verified it myself, but I'm letting you know before looking at it, because if you see a quick fix.

**Comment by yvanoers** [comment]
@victorcoder Interesting, I'll have a look tonight.
Am I correct in assuming that the graph represents the number of jobs executed on 3 different servers (a different color for each server)?

**Comment by victorcoder** [comment]
@yvanoers yes, correct, it changed colors because of node restart, switching leader, jobs are mostly executed on the leader

**Comment by yvanoers** [comment]
@victorcoder I found the problem, I will create a pull request shortly.

**Pull request merged**
