### PR TITLE
add kafka and nats executer

### PR DESCRIPTION
**Pull request by mariam-monier-web**

### CODE REVIEW

**Comment by victorcoder** [comment]
Thanks @mariam-monier-web !

I just enabled GH Actions to run on PRs, could you merge from master and reopen the PR to force a build?

**Comment by cubita-io** [comment]
when support???

**Comment by yvanoers** [comment]
@cubita-io Probably not long after the tests in this PR are shown to pass. We're still waiting on @mariam-monier-web to reopen this PR so tests will be run.

**Comment by fopina** [comment]
executors are plugins, does it make sense to merge them into the main project, besides the core ones?

**Comment by cobolbaby** [comment]
@mariam-monier-web Any progress?

**Comment by mariam-monier-web** [comment]
@victorcoder , Now i reopen PR and All checks have passed
link of PR  at  https://github.com/distribworks/dkron/pull/686

**Pull request closed without merging**
