### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by KevinWu0904**

### CODE REVIEW

**Comment by yvanoers** [comment]
If you have any more typo fixes, please collect them in this PR and we can merge them in one go.

**Review by victorcoder — DISMISSED** [review]
LGTM thanks!

**Comment by KevinWu0904** [comment]
@yvanoers Make sense to me. I already go through the project and find those typo, feel free to review. Thanks !

**Review by fopina — APPROVED** [review]

**Review by yvanoers — APPROVED** [review]

**Comment by yvanoers** [comment]
@KevinWu0904  Thanks!

**Pull request merged**
