### PR TITLE
Enhance Kafka Executor config with SASL Authentication

### PR DESCRIPTION
**Pull request by mikekosulin**
Add support for SASL authentication in the Kafka Executor, allowing users to configure secure connections using SASL mechanisms like `SCRAM-SHA-256`/`SCRAM-SHA-512`.

### CODE REVIEW

**Comment by vcastellm** [comment]
Hi, sorry about the delay, can you rebase with main?

**Comment by mikekosulin** [comment]
Hey, 
rebased with main, thanks!

**Comment by mikekosulin** [comment]
any updates?

**Review by vcastellm — APPROVED** [review]
LGTM thx!

**Pull request merged**
