### PR TITLE
real-time prometheus metrics from job executions

### PR DESCRIPTION
**Pull request by andreygolev**
This an initial PR for all metrics we get from shell job executions.

We do have more prometheus metrics that are extracted from finished jobs, but it's better to add them via another PR which depends on this PR.

* Job execution spent time
* Exit code
* Last execution timestamp (useful for alerting in case job is not successfully finished in expected time)

### CODE REVIEW

**Comment by cobolbaby** [comment]
@vcastellm 

Is it possible to consider merging this feature.

**Comment by vcastellm** [comment]
@andreygolev let us know if you want to work on this or we should take over, thanks.

**Comment by cobolbaby** [comment]
@vcastellm Could you please take over?

**Comment by vcastellm** [comment]
Taking over

**Pull request closed without merging**
