### PR TITLE
Fix XSS vulnerability

### LINKED ISSUE #921: XSS injection in output panel
**Describe the bug**
Dashboard is vulnereable by XSS injection

**To Reproduce**
1. Run a job that outputs some html and/or js.  like `echo <script>alert('xss')</script>`
2. Check execution output in dashboard
3. Get an XSS injection in your browser

**Expected behavior**
Page with escaped job output instead of injected raw html.

### PR DESCRIPTION
**Pull request by yvanoers**
Fixes #921.

The original code seemed to deliberately use unescaped HTML. I'm hoping that was accidental and this doesn't break anything.

### CODE REVIEW

**Review by victorcoder — APPROVED** [review]
I remember that I went for the unsafe option, but I don't know why, have you checked the output reads correctly and is well formatted?

**Comment by yvanoers** [comment]
I checked that the output gets encoded properly. Judge for yourself:
Before:
image
After:
image

**Review by victorcoder — APPROVED** [review]
LGTM thanks!

**Comment by sc0rp10** [comment]
@victorcoder could you please also tag a release with that fix?

**Pull request merged**
