### PR TITLE
shutdown raft util all backgroud routines have exited

### PR DESCRIPTION
**Pull request by vision9527**
shutdown raft util all backgroud routines have exited

### CODE REVIEW

**Comment by fopina** [comment]
Is this meant to stop receiving new tasks but let current ones finish?
Would it still be able to update leader with jobs output with raft shutdown?

**Comment by vision9527** [comment]
> Is this meant to stop receiving new tasks but let current ones finish?
> Would it still be able to update leader with jobs output with raft shutdown?

image
This is used in consul.
image
This is about raft Shutdown description.

**Review by victorcoder — COMMENTED** [review]
thx @vision9527! LGTM but can you check why the CI breaks?

**Comment by vision9527** [comment]
> thx @vision9527! LGTM but can you check why the CI breaks?

I have no idea about the CI error. It seems not due to my code.

**Review by victorcoder — COMMENTED** [review]
@vision9527 can you rebase with master? that should fix the CI then, thank you.

**Comment by vision9527** [comment]
@victorcoder I have merged master, but still not work.

**Comment by victorcoder** [comment]
This still applies, @vision9527 do you want to rebase with master and try the build again? Thanks

**Comment by vcastellm** [comment]
Superseded by a TODO because this doesn't work

**Pull request closed without merging**
