### PR TITLE
Fix new jobs showing as failed in dashboard in western timezones

### LINKED ISSUE #576: Failed jobs count increasing with new jobs added - v2.0.0-b5
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

## Expected Behavior
When adding jobs, if they have not run yet, **should not increase** failed jobs count

## Actual Behavior
For each new job added, it increases failed job count 

## Steps to Reproduce the Problem

  1. Add a job via API
  2. Failed job count increases

## Specifications

  - Version:v2.0.0-b5
  - Platform:linux
  - Backend store:default

### PR DESCRIPTION
**Pull request by yvanoers**
Fixes #576 .

This time around, chose not use the 0001-01-01 date to have special meaning, but it either is a Date or it is null. As a bonus, the Last Execution column now says "never" for jobs that have not run yet.

### CODE REVIEW

**Comment by viperfx** [comment]
@victorcoder I would be happy to test this and verify with a new beta release

**Comment by viperfx** [comment]
@yvanoers seems like there are some conflicts with v2 branch

**Comment by yvanoers** [comment]
@viperfx Thanks for bringing it to my attention. @victorcoder has been busy the last couple of days :) I will resolve the conflicts asap, probably tonight.

**Comment by victorcoder** [comment]
Been quite busy polishing details in the UI, with the latest changes for the UI and this PR, I think we are set for the RC ^___^

**Comment by yvanoers** [comment]
@victorcoder Thank you for the compliment!

Conflicts are resolved, merge at will!

**Comment by victorcoder** [comment]
@yvanoers I detected that this breaks job edit in the UI because when editing because of `json: cannot unmarshal string into Go struct field Job.last_error of type ntime.NullableTime`

**Comment by yvanoers** [comment]
@victorcoder Rats. I will look into it and come up with a fix.

**Pull request merged**
