### PR TITLE
V2.x cronv3

### PR DESCRIPTION
**Pull request by yvanoers**
Upgrades cron to v3 (#549).
Factors out dkron specific scheduling options.
Removes Cron interface.
Contains minor improvement to SimpleSchedule.

### CODE REVIEW

**Comment by yvanoers** [comment]
@victorcoder Each commit is a separate step in the upgrade, commit messages should speak for themselves. Please have a look, appreciate your feedback.

**Comment by yvanoers** [comment]
Closing & reopening to force rebuild

**Comment by yvanoers** [comment]
@victorcoder Rebased and passed CI.
Commits e2f5589 and 17b4624 could be squashed, if you like?

**Comment by victorcoder** [comment]
My tests are successful with this modification. As this has been implemented in a way it doesn't have any breaking change, I'm going to merge this into v2

**Comment by yvanoers** [comment]
@victorcoder FYI: PR for cron: [cron/#243](https://github.com/robfig/cron/pull/243).

**Pull request merged**
